name: Streamlit
description: Run a Streamlit app inside CML.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-03-24"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install Dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    arguments: None
    cpu: 2
    memory: 4
    short_summary: Create job to install project dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_dependencies
    short_summary: Run install dependencies job.
    long_summary: Run install dependencies job.

  - type: start_application
    name: Streamlit App
    subdomain: streamlit
    script: cml/launch_app.py
    short_summary: Start Streamlit application
    environment_variables:
      TASK_TYPE: START_APPLICATION
